### ISSUE TITLE
Hadolint consideration leaves the check in failed state

### ISSUE THREAD

**Issue by cdupuis** [atomist-skills/docker-file-policy#36]
The skill suggests to combine the following two `RUN` lines:

```
RUN curl -s -L -O https://github.com/Yelp/dumb-init/releases/download/v$DUMB_INIT_VERSION/dumb-init_${DUMB_INIT_VERSION}_amd64.deb     && dpkg -i dumb-init_${DUMB_INIT_VERSION}_amd64.deb     && rm -f dumb-init_${DUMB_INIT_VERSION}_amd64.deb

RUN mkdir -p /app
```

I don't think the suggestion is a good idea as logically both `RUN` commands are dealing with something entirely different. Yet the corresponding annotation is at warning level and the check is in failed state: https://github.com/cdupuis-test/cd-spring-11/runs/2525134792

I _think_ the annotation should be notice and the check in neutral if not successful.

**Comment by kipz** [comment]
| I think the annotation should be notice and the check in neutral if not successful. 

going to reduce to neutral for now

**Comment by slimslenderslacks** [comment]
@cdupuise just FYI on the intersection between `WORKDIR /app` and `RUN mkdir` instructions 
In the above case, the RUN mkdir might be redundant because you already have the instruction `WORKDIR /app` and according to the spec, that directory will be created simply by adding that instruction (I have verified this is true by cloning your project removing the RUN mkdir instructions and building).  I think you can  delete that line and remove a layer

^ understand that this is not a general solution to the problem you found.  I'm also softening the failed state when the violations are at the info, ignore, or style severity levels.

**Comment by slimslenderslacks** [comment]
Now logging the severity level and only failing check if a violation is at error or warning level.
