### ISSUE TITLE
Pending check run when processing large numbers of Dockerfiles

### ISSUE THREAD

**Issue by cdupuis** [atomist-skills/docker-file-policy#94]
https://github.com/cdupuis-test/scale/runs/3301123388

**Comment by slimslenderslacks** [comment]
I think we only leave CheckRuns in pending states when the underlying skill is killed.  @cdupuis do you know if my parent node process will get a SIGTERM when CloudRun stops it because of memory?  I could potentially detect that there's still a pending CheckRun running with a SIGTERM handler.  Have you experimented with this?
I've added the handler in any case, I can at least verify that if the root process in the container gets a SIGTERM, I won't leave behind any pending checkruns now.  I don't have a simple way of testing this on Cloudrun right now.
